# --- Cell 3: imports and dataset loading ---
# pandas/NumPy manage tabular numeric data; matplotlib/seaborn draw the evaluation charts.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import os

from sklearn.model_selection import train_test_split
from sklearn.ensemble import (RandomForestClassifier, GradientBoostingClassifier,
                               RandomForestRegressor)
from sklearn.metrics import (accuracy_score, f1_score, classification_report,
                              confusion_matrix, r2_score, mean_absolute_error)

# Let notebook tables show every column while exploring the dataset.
pd.set_option('display.max_columns', None)

# This file is generated by notebook 02 and already contains clean/encoded features.
df = pd.read_csv("../data/processed/featured_dataset.csv")
print("Shape:", df.shape)
df.head()

# --- Cell 5 ---
# TARGET (y) = what we want to predict: the risk tier P1-P4.
# X = the inputs. I drop the id, the target itself, the raw text columns (kept their
# encoded versions), the raw income (kept the capped one) and the display-only bins.
TARGET = 'Approved_Flag'
DROP_COLS = ['PROSPECTID', TARGET, 'NETMONTHLYINCOME',
             'MARITALSTATUS', 'EDUCATION', 'GENDER', 'last_prod_enq2', 'first_prod_enq2',
             'Age_Group', 'Income_Segment', 'Credit_Score_Band']
FEATURE_COLS = [c for c in df.columns if c not in DROP_COLS]
print(f"{len(FEATURE_COLS)} features:")
print(FEATURE_COLS)

X = df[FEATURE_COLS]   # the 68 input columns
y = df[TARGET]         # the answer we're training the model to predict

# --- Cell 7 ---
# Split the data into 3 parts so I test the model on data it has NEVER seen:
#  - Train (70%)      -> the model learns from this
#  - Validation (15%) -> used to pick the best algorithm
#  - Test (15%)       -> only touched once at the very end for an honest score
# stratify=y keeps the P1-P4 mix the same in every part. random_state=42 = reproducible.
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y, test_size=0.30, stratify=y, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42)

print(f"Train: {len(X_train):,}  Validation: {len(X_val):,}  Test: {len(X_test):,}")
print(f"Total: {len(X_train) + len(X_val) + len(X_test):,} (dataset has {len(df):,} rows)")

# --- Cell 9 ---
# The risk-tier model. Gradient Boosting was the best performer in development, so it
# is the single classifier the project trains and ships.
classifiers = {
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=100, max_depth=3, random_state=42),
}

clf_results = []
fitted_classifiers = {}
for name, clf in classifiers.items():
    clf.fit(X_train, y_train)              # train on the training set
    val_pred = clf.predict(X_val)          # predict on the validation set
    acc = accuracy_score(y_val, val_pred)  # how often it was right
    f1 = f1_score(y_val, val_pred, average='macro')   # balanced score across all 4 tiers
    clf_results.append({"Model": name, "Val_Accuracy": acc, "Val_F1_Macro": f1})
    fitted_classifiers[name] = clf
    print(f"{name:22s} val_accuracy={acc:.4f}  val_f1_macro={f1:.4f}")

clf_results_df = pd.DataFrame(clf_results).sort_values('Val_Accuracy', ascending=False)
clf_results_df

# --- Cell 11 ---
# Take the winner from the validation round and give it the final exam on the TEST
# set (data it has never seen). This is the honest, real-world accuracy to report.
best_clf_name = clf_results_df.iloc[0]['Model']
best_clf = fitted_classifiers[best_clf_name]
print(f"Best model on validation: {best_clf_name}")

test_pred = best_clf.predict(X_test)
test_acc = accuracy_score(y_test, test_pred)
print(f"\nTest accuracy: {test_acc:.4f}\n")
# classification_report shows precision/recall/F1 for each tier separately
print(classification_report(y_test, test_pred))

# --- Cell 12: confusion-matrix chart ---
# A confusion matrix shows which actual tiers the classifier confuses with other tiers.
cm = confusion_matrix(y_test, test_pred, labels=['P1', 'P2', 'P3', 'P4'])
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['P1','P2','P3','P4'],
            yticklabels=['P1','P2','P3','P4'])
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title(f'Confusion Matrix — {best_clf_name} (Test Set)')
plt.tight_layout()
plt.savefig('../figures/confusion_matrix.png', dpi=120)
plt.show()

# --- Cell 14: model explainability ---
# Tree models expose feature_importances_; this block ranks and saves them for the dashboard.
if hasattr(best_clf, 'feature_importances_'):
    importances = pd.DataFrame({
        'Feature': FEATURE_COLS,
        'Importance': best_clf.feature_importances_
    }).sort_values('Importance', ascending=False).reset_index(drop=True)
    importances['Importance_Pct'] = (importances['Importance'] / importances['Importance'].sum() * 100).round(3)
    importances.insert(0, 'Rank', importances.index + 1)

    plt.figure(figsize=(8, 10))
    sns.barplot(data=importances.head(25), x='Importance', y='Feature')
    plt.title(f'Top 25 Feature Importances — {best_clf_name}')
    plt.tight_layout()
    plt.savefig('../figures/feature_importance.png', dpi=120)
    plt.show()

    importances.to_csv('../reports/feature_importance.csv', index=False)
    display(importances.head(15))
else:
    print(f"{best_clf_name} has no feature_importances_ attribute")

# --- Cell 16: transparent bank policy table ---
# These rules are not learned by ML. They are explicit lending-policy assumptions that
# turn a predicted tier into a rate, tenure, cap, and repayment-method recommendation.
TIER_RULES = pd.DataFrame([
    dict(RiskTierID='P1', Risk_Category='Best Risk',     Eligibility_Status='Approved',
         Max_Loan_Amount=2_500_000, Interest_Rate_Pct=8.5,  Tenure_Years=5,
         Repayment_Method='EMI Fixed Monthly',  Income_Multiplier=5.0, Risk_Score_Range='750+'),
    dict(RiskTierID='P2', Risk_Category='Good Risk',     Eligibility_Status='Approved',
         Max_Loan_Amount=1_500_000, Interest_Rate_Pct=10.5, Tenure_Years=4,
         Repayment_Method='EMI Fixed Monthly',  Income_Multiplier=3.5, Risk_Score_Range='700-749'),
    dict(RiskTierID='P3', Risk_Category='Moderate Risk', Eligibility_Status='Conditional',
         Max_Loan_Amount=750_000,   Interest_Rate_Pct=13.5, Tenure_Years=3,
         Repayment_Method='EMI Step-Up',        Income_Multiplier=2.0, Risk_Score_Range='650-699'),
    dict(RiskTierID='P4', Risk_Category='High Risk',     Eligibility_Status='Rejected',
         Max_Loan_Amount=200_000,   Interest_Rate_Pct=18.0, Tenure_Years=2,
         Repayment_Method='Secured/Collateral', Income_Multiplier=0.5, Risk_Score_Range='<650'),
]).set_index('RiskTierID')

# Create the reports folder if it does not exist, then save the policy for the app.
os.makedirs('../reports', exist_ok=True)
TIER_RULES.to_csv('../reports/dim_risk_tier.csv')
TIER_RULES

# --- Cell 17: safe-loan target generation ---
# The historical data does not provide a known "correct" loan amount. We therefore
# construct a defensible target from policy, income, risk health, and affordability.
def risk_adjustment(credit_health_score):
    """Convert 0-100 credit health to a conservative 0.6-1.0 amount multiplier."""
    return np.clip(0.6 + 0.4 * (credit_health_score / 100.0), 0.6, 1.0)

IDEAL_FOIR = 0.30  # ideal/safe zone: EMI under 30% of income for every income level

def max_foir(net_monthly_income=None):
    """EMI ceiling as a share of net monthly income. We size to the *ideal zone* --
    a flat 30% for everyone (low or high earner) -- so that after the EMI, basic
    needs (food, rent, utilities, education) and monthly savings stay unaffected."""
    return IDEAL_FOIR

def affordable_loan(net_monthly_income, annual_rate_pct, tenure_years):
    """Largest loan whose EMI stays within the FOIR limit for this income. Uses the
    customer's ACTUAL stated income so the EMI is genuinely affordable."""
    if net_monthly_income <= 0:
        return 0.0
    max_emi = max_foir(net_monthly_income) * net_monthly_income  # 30% income ceiling
    r = (annual_rate_pct / 100.0) / 12.0
    n = tenure_years * 12
    if r == 0:
        return max_emi * n
    # Rearranged EMI formula: principal that can be supported by ``max_emi``.
    annuity_factor = ((1 + r) ** n - 1) / (r * (1 + r) ** n)
    return max_emi * annuity_factor

def target_loan_amount(row):
    rule = TIER_RULES.loc[row[TARGET]]
    # A credit-risk factor from Credit_Health_Score (weaker payment history -> lower
    # factor -> smaller loan). Applied to BOTH the income-multiple and the
    # affordability limit, so credit history genuinely changes the amount.
    risk = risk_adjustment(row['Credit_Health_Score'])
    # income-multiple uses capped income (tames high-side data outliers);
    # affordability uses raw income (the real cashflow the EMI must fit within)
    by_income = row['NETMONTHLYINCOME_Capped'] * 12 * rule['Income_Multiplier'] * risk
    by_affordability = affordable_loan(row['NETMONTHLYINCOME'], rule['Interest_Rate_Pct'], rule['Tenure_Years']) * risk
    # smallest of: income-multiple, tier cap, risk-adjusted EMI affordability
    return min(by_income, rule['Max_Loan_Amount'], by_affordability)

# Apply the policy function to every customer; this becomes the regression label y_amt.
df['Target_Loan_Amount'] = df.apply(target_loan_amount, axis=1)
print(df['Target_Loan_Amount'].describe())

y_amt = df['Target_Loan_Amount']
Xr_train, Xr_temp, yr_train, yr_temp = train_test_split(X, y_amt, test_size=0.30, random_state=42)
Xr_val, Xr_test, yr_val, yr_test = train_test_split(Xr_temp, yr_temp, test_size=0.50, random_state=42)

# --- Cell 18: loan-amount regressor ---
# Monotonic constraint: a higher credit score / credit-health score must never LOWER the
# recommended loan. A plain Random Forest is not guaranteed monotonic, which caused a tiny
# non-monotonic dip at very high (data-sparse) credit scores. +1 = "can only push the loan up".
MONO_UP = ['Credit_Score', 'Credit_Health_Score']
monotonic_cst = [1 if c in MONO_UP else 0 for c in FEATURE_COLS]

regressors = {
    "Random Forest Regressor": RandomForestRegressor(n_estimators=50, max_depth=12, min_samples_leaf=8,
                                                     monotonic_cst=monotonic_cst, random_state=42, n_jobs=-1),
}

reg_results = []
fitted_regressors = {}
for name, reg in regressors.items():
    reg.fit(Xr_train, yr_train)   # learn the policy-generated target from customer features
    val_pred = reg.predict(Xr_val)  # evaluate only on validation customers
    r2 = r2_score(yr_val, val_pred)
    mae = mean_absolute_error(yr_val, val_pred)
    reg_results.append({"Model": name, "Val_R2": r2, "Val_MAE": mae})
    fitted_regressors[name] = reg
    print(f"{name:25s} R2={r2:.4f}  MAE={mae:,.0f}")

reg_results_df = pd.DataFrame(reg_results).sort_values('Val_R2', ascending=False)
reg_results_df

# --- Cell 19: final regression test and fitted-value chart ---
best_reg_name = reg_results_df.iloc[0]['Model']
best_reg = fitted_regressors[best_reg_name]
print(f"Best regressor on validation: {best_reg_name}")

test_pred = best_reg.predict(Xr_test)
test_r2 = r2_score(yr_test, test_pred)
test_mae = mean_absolute_error(yr_test, test_pred)
print(f"Test R2: {test_r2:.4f}   Test MAE: Rs.{test_mae:,.0f}")

plt.figure(figsize=(6, 6))
plt.scatter(yr_test, test_pred, alpha=0.15, s=8)
lims = [0, max(yr_test.max(), test_pred.max())]  # identical x/y scale for the perfect-fit diagonal
plt.plot(lims, lims, 'r--')
plt.xlabel('Target Loan Amount')
plt.ylabel('Predicted Loan Amount')
plt.title(f'{best_reg_name} — Predicted vs Target (Test Set)')
plt.tight_layout()
plt.savefig('../figures/loan_amount_regression.png', dpi=120)
plt.show()

# --- Cell 21: persist model metrics for the dashboard ---
performance_rows = [
    ("Task", "Risk tier classification (Approved_Flag)"),
    ("Best Classifier", best_clf_name),
    ("Train Size", len(X_train)),
    ("Validation Size", len(X_val)),
    ("Test Size", len(X_test)),
    ("Total Features", len(FEATURE_COLS)),
    ("Target Classes", "P1, P2, P3, P4"),
    ("Test Accuracy", f"{test_acc*100:.2f}%"),
    ("Task ", "Loan amount regression"),
    ("Best Regressor", best_reg_name),
    ("Regression Test R2", f"{test_r2:.4f}"),
    ("Regression Test MAE", f"Rs.{test_mae:,.0f}"),
]
model_performance_df = pd.DataFrame(performance_rows, columns=["Metric", "Value"])
model_performance_df.to_csv('../reports/model_performance.csv', index=False)

# save the model metrics tables
clf_results_df.to_csv('../reports/classifier_comparison.csv', index=False)
reg_results_df.to_csv('../reports/regressor_comparison.csv', index=False)

model_performance_df

# --- Cell 23: persist trained artifacts ---
os.makedirs('../models', exist_ok=True)

# Save ONLY the single best model of each task -- these are the two the dashboard uses:
# Gradient Boosting for the risk tier, Random Forest Regressor for the loan amount.
# (The other algorithms were trained purely for the comparison above, not kept on disk.)
joblib.dump(best_clf, '../models/risk_tier_classifier.joblib', compress=3)
joblib.dump(best_reg, '../models/loan_amount_regressor.joblib', compress=3)
joblib.dump(FEATURE_COLS, '../models/feature_columns.joblib')
print(f"Saved the two best models: {best_clf_name} (classifier), {best_reg_name} (regressor)")

# --- Cell 25: build a reduced feature set for an external file with fewer columns ---
# The unseen spreadsheet lacks several full-model fields, so it needs its own model.
unseen_df = pd.read_excel('../data/raw/Unseen_Dataset.xlsx')
unseen_cols = set(unseen_df.columns)

CAT_ENC_MAP = {'MARITALSTATUS_enc': 'MARITALSTATUS', 'EDUCATION_enc': 'EDUCATION',
               'GENDER_enc': 'GENDER', 'last_prod_enq2_enc': 'last_prod_enq2',
               'first_prod_enq2_enc': 'first_prod_enq2'}

reduced_feature_cols = [c for c in FEATURE_COLS if c in unseen_cols]
for enc_col, raw_col in CAT_ENC_MAP.items():
    if raw_col in unseen_cols and enc_col not in reduced_feature_cols:
        reduced_feature_cols.append(enc_col)

missing_from_unseen = [c for c in FEATURE_COLS if c not in reduced_feature_cols]
print(f"Reduced feature set: {len(reduced_feature_cols)} of {len(FEATURE_COLS)} columns available in Unseen_Dataset")
print(f"Columns NOT available for unseen scoring (including 'Credit_Score'): {len(missing_from_unseen)}")
print(missing_from_unseen)

# --- Cell 26: train and save a fallback reduced-feature classifier ---
Xr_full = df[reduced_feature_cols]
Xr_train2, Xr_val2, yr_train2, yr_val2 = train_test_split(
    Xr_full, y, test_size=0.15, stratify=y, random_state=42)

reduced_clf = RandomForestClassifier(n_estimators=200, max_depth=12, random_state=42, n_jobs=-1)
reduced_clf.fit(Xr_train2, yr_train2)
reduced_val_pred = reduced_clf.predict(Xr_val2)
reduced_acc = accuracy_score(yr_val2, reduced_val_pred)
print(f"Reduced-feature model validation accuracy: {reduced_acc:.4f} "
      f"(vs {test_acc:.4f} for the full-feature model — expected drop since "
      f"Credit_Score itself is unavailable)")

joblib.dump(reduced_clf, '../models/risk_tier_classifier_reduced.joblib')
joblib.dump(reduced_feature_cols, '../models/reduced_feature_columns.joblib')
print("Saved reduced-feature model for unseen scoring.")
